# This playbook will install our master of kubernetes cluster

  - name: Install Kubernetes
    shell: kubeadm init --apiserver-advertise-address={{ k8s_master_ip }} --pod-network-cidr=192.168.0.0/16

  - name: Create .kube directory
    file:
      path: /home/ubuntu/.kube
      state: directory
      mode: 0755

  - name: Copy admin.conf file to /.kube/config
    shell: sudo cp /etc/kubernetes/admin.conf /home/ubuntu/.kube/config

  - name: Change ownership on /.kube/config
    file:
      path: /home/ubuntu/.kube/config
      owner: ubuntu
      group: ubuntu

  - name: Install rbac-kdd
    shell: kubectl apply -f https://docs.projectcalico.org/v3.3/getting-started/kubernetes/installation/hosted/rbac-kdd.yaml
    become: true
    become_user: ubuntu

  - name: Install rbac-kdd
    shell: kubectl apply -f https://docs.projectcalico.org/v3.3/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico-networking/1.7/calico.yaml
    become: true
    become_user: ubuntu

  - name: get join command
    shell: kubeadm token create --print-join-command
    register: join_command_raw

  - name: set join command
    set_fact:
      join_command: "{{ join_command_raw.stdout_lines[0] }}"



