
  - name: "APT - install misc packages"
    apt:
      name: ['apt-transport-https','ca-certificates','curl','software-properties-common','gnupg-agent']
      update_cache: yes

  - name: APT - Add Docker GPG key
    apt_key:
      id: 0EBFCD88
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: "APT - Add Docker repository"
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
      state: present
      filename: docker

  - name: "APT - install 'docker-ce'"
    apt:
      name: ['docker-ce','docker-ce-cli','containerd.io']
      update_cache: yes

