

  - name: Update the software package repository & Install dependencies
    apt:
      update_cache: yes
      name: ['curl','net-tools','unzip']
    
  - name: Install consul - Download consul binary & Unzip 
    unarchive:
      src: https://releases.hashicorp.com/consul/1.9.1/consul_1.9.1_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes

  - name: delete zip file
    command: sudo rm -f  /usr/local/bin/consul_1.2.0_linux_amd64.zip # check the version to be deleted if at all

  - name: Create Consul server directory
    file:
      path: /etc/consul.d/server
      state: directory
      mode: 0755

  - name: Copy systemd bootstrap consul.service
    template: 
      src: node-consul.service.j2
      dest: /etc/systemd/system/consul.service

  - name: Copy configuration file
    template:
      src: config.json.j2
      dest: /etc/consul.d/server/config.json

  - name: Start Consul service
    systemd:
      name: consul
      state: started

